config/routes.rb
Rails.application.routes.draw do
 root "colleges#index"
 get ":id", to:"colleges#show", as:"college"
 post "add_card/:id", to:"colleges#add_card"
 get "card", to:"cards#card"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :colleges
end

app/models/college.rb
class College < ApplicationRecord
  enum level: [:a1, :a2, :b1, :b2, :c1, :c2]
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def card
    @card = Card.find(1)
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  def index
    @colleges = College.all
  end
  def show
    @college = College.find(params[:id])
  end
  def add_card
    college = College.find(params[:id])
    college.update(card_id:1)
    redirect_to root_path
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/index.html.erb
 <% @colleges.each do |college| %>
<%= college.price %>
<%= college.level %>
<%= college.country %>
<%= college.boarding %>
<%= college.language %>
<%= link_to "show",college_path(college) %>
<%= link_to "card",add_card_path(college) %>
 <% end %>

app/views/colleges/show.html.erb
<%=@college.id%>
<%=@college.price%>
<%=@college.country%>
<%=@college.language%>
<%=@college.level%>
<%=@college.boarding%>
<%=link_to "add_card" , add_card_path(@college.id), method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seller</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>